Add sanity checks and error messages

diff --git a/drone-secrets b/drone-secrets
--- a/drone-secrets
+++ b/drone-secrets
@@ -2,9 +2,22 @@
 set -e
 set -o pipefail
 
+# Only use error colours when stdout is a tty
+if [ -t 2 ]; then
+    RED='\033[0;31m'
+    NC='\033[0m'
+fi
+
+error() { >&2 printf "${RED}${MSG:-Error}: $@${NC}"; exit 1; }
+
 if [ $# -lt 1 ]; then
-    >&2 echo "Usage: $(basename $0) <repo e.g. spritsail/test>"
-    exit 1
+    MSG=Usage error "$(basename $0) <repo e.g. spritsail/test> [docker image repo]"
+elif [ -z "$DRONE_SERVER" ]; then
+    error "DRONE_SERVER variable is unset"
+elif [ -z "$DRONE_TOKEN" ]; then
+    error "DRONE_TOKEN variable is unset"
+elif ! docker info >/dev/null 2>&1; then
+    error "docker daemon isn't running"
 fi
 
 REPO="$1"
